language: node_js
node_js:
  - "8"
services:
  - docker
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - docker build -t humanconnection/frontend-nuxt:alpha .
install:
  - yarn install --frozen-lockfile --non-interactive
  - yarn test:env
  - yarn test
after_success:
  # only deoloy when pushing to master but not on pull-requests
  - if [ "$TRAVIS_BRANCH" == "master" ] AND type IN (push); then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push humanconnection/frontend-nuxt:alpha;
    fi
#  - yarn run coverage
