language: node_js
node_js:
  - "9"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn run test
services:
  - docker
before_install:
  - docker build -t humanconnection/frontend-nuxt .
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push humanconnection/frontend-nuxt;
    fi
#- yarn run coverage