language: node_js
node_js:
  - "8"
services:
  - docker
cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    - stage: Test and Build
      script:
      - yarn install --frozen-lockfile --non-interactive
      - yarn test:env
      - yarn test
    - script:
      - docker build -t humanconnection/frontend-nuxt:alpha .
    - stage: Deploy
      if: branch = master AND type IN (push)
      script:
        # only deoloy when pushing to master but not on pull-requests
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
        docker push humanconnection/frontend-nuxt:alpha;
        fi
