version: '2'

services:
  frontend:
    build: .
    environment:
      PORT: 3100
      BASE_URL: http://localhost:3100
      API_HOST: http://localhost
      API_PORT: 3033
      MAPBOX_TOKEN:
    stdin_open: true
    tty: true
    ports:
    - 3000:3000/tcp
